info:
  name: Post Tasks
  type: http
  seq: 2

http:
  method: POST
  url: "{{baseUrl_publicApi}}/api/v2/tasks"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
